update ci/cd script

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -40,11 +40,30 @@ jobs:
           key: ${{ secrets.VPS_SSH_KEY }}
           port: 22
           script: |
-            # Pull the latest image from Docker Hub
-            if docker pull pardes29/koistory-api:v1; then
-                echo "Image pulled successfully."
-            else
-                echo "Failed to pull image."
+            # check internet connection to Docker Hub
+            if ! ping -c 3 registry-1.docker.io; then
+                echo "Kết nối mạng đến Docker Hub thất bại. Thoát."
+                exit 1
+            fi
+
+            # retry 3 times when pulling Docker image with maximum wait time of 60 second each time
+            RETRY_COUNT=0
+            MAX_RETRIES=3
+            until [ $RETRY_COUNT -ge $MAX_RETRIES ]
+            do
+              if timeout 60 docker pull pardes29/koistory-api:v1; then
+                  echo "Pull image successfully."
+                  break
+              else
+                  echo "Image pull failed. Try again in 7 seconds..."
+                  RETRY_COUNT=$((RETRY_COUNT + 1))
+                  sleep 7
+              fi
+            done
+
+            # Exit if maximum number of attempts reached
+            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+                echo "Unable to pull image after $MAX_RETRIES attempts"
                 exit 1
             fi
 
